# 接口起始路径
api: "/api"

# 前端静态资源
webPath: "/src/public/dist"

# 用户会话配置
session:
  # 有效时间(单位毫秒), 6小时
  maxAge: 21600000
  # 活跃状态自动延长
  activeExtend: true
  # 同个账号最大同时登录设备
  accountActiveNum: 2

# ip 名单配置, 在时间范围内且达到最大访问次数则标记为频繁访问, 若在时间范围内且达到 deathCount 则进行拉黑处理
ipList:
  # 时间范围(单位毫秒), 10秒
  maxAge: 10000
  # 最大频繁访问次数
  maxCount: 10
  # 最大拉黑访问次数
  deathCount: 20

# 初始账号密码
root:
  account: "root"
  password: "123456"
